
                                                             NUMPY
It is a fundamental library for Scientific Calculations in Python.
It providesupport for Arrays and Matrices along with collection of Mathematical functions to operate over these Data Structure.
                                                             

In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1)) ## type --> for type of array
print(arr1.shape) ## .shape--> for dimension of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 colums
print(arr2)
arr2.shape


[1 2 3 4 5]


(5,)

In [5]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
arr5=np.arange(0,10,2) # 0-->start from zero(inclusive),10-->go till 10 (exclusive),2-->jump two numbers.
print(arr5) #arange function creates continous array.

[0 2 4 6 8]


In [7]:
arr5.reshape(5,1) # Here new copy is formed .


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4)) # creates an array of one i.e-->1 of given dimension.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(3) # creates identity matrix of given dimension.


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(4,5,2) #eye(n,m,p) n-->no of rows.  m -->no of colums(optional) .  p-->from which column we have to pave 1(optional).

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [11]:
arr6=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr6)
print("dimesion of array:",arr6.shape)           # .shape
print("dimension i.e 1d,2d..:",arr6.ndim)        #.ndim
print("size(number of elements):",arr6.size)     # .size
print("Data type:",arr6.dtype)                   #.dtype
print("size of each elements:",arr6.itemsize)    # .itemsize
#Above are the Attributes of Numpy ARRAY.


[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimesion of array: (3, 3)
dimension i.e 1d,2d..: 2
size(number of elements): 9
Data type: int64
size of each elements: 8


In [12]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
## array slicing and Indexing

arr6=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr6)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr6[1:,1:3]) # 3 is exclusive

[[ 6  7]
 [10 11]]


In [16]:
print(arr6[0][0])
print(arr6[0:2,2:])

1
[[3 4]
 [7 8]]


In [17]:
arr6[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [18]:
## Modify array elements
arr6[0,0]=100
print(arr6)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr6[1:]=100
print(arr6)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [20]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [21]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)                              #np.mean()
print("Mean:", mean)

# Median
median = np.median(data)                          #np.median()
print("Median:", median)

# Standard deviation
std_dev = np.std(data)                             #np.std()
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)                           #np.var()
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [22]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])